# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-23 17:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineLoader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('storage', models.CharField(choices=[('files', 'File System'), ('AWS', 'Amazon S3'), ('GCP', 'Google Storage')], max_length=20)),
                ('file_type', models.CharField(choices=[('CSV', 'CSV'), ('JSON', 'JSON'), ('XML', 'XML')], max_length=20)),
                ('file_path', models.CharField(max_length=200)),
                ('field_mappings', jsonfield.fields.JSONField(default=dict, help_text='Enter JSON Dictionary [Example: {"a":"b", "c":"d"}]')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('updated_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('job', models.ManyToManyField(to='loader.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('updated_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('offline_loader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_offlineloader', to='loader.OfflineLoader')),
            ],
            options={
                'verbose_name': 'Project',
            },
        ),
        migrations.CreateModel(
            name='TwitterTracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('search_terms', models.TextField(max_length=500)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('updated_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('job', models.ManyToManyField(to='loader.Job')),
            ],
            options={
                'verbose_name': 'Twitter Track',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='twitter_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_twittertracks', to='loader.TwitterTracks'),
        ),
    ]
